const VALID_PERMISSIONS = [
    'ACCESS_ADMIN_PANEL',
    'ACCESS_MANAGE_USERS',
    'ACCESS_MANAGE_ROLES',
    'ACCESS_MANAGE_EXERCISES',
    'ACCESS_MANAGE_CATEGORIES',
    'ACCESS_MANAGE_SCHEDULE',
    'ACCESS_MANAGE_DOCUMENTS',
    'ACCESS_LOGIN_ADMIN', 
  ];
  
module.exports = VALID_PERMISSIONS;
  